[project]
name = "example"
version = "0.1.0"
description = "Example scripts for using the batsim package"
requires-python = ">=3.13"
dependencies = [
    "batsim",
    "notebook==7.4.5",
    "pandas[excel]==2.3.2",
]

[tool.uv.sources]
batsim = { path = "../batsim" }
